name: Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
    - uses: actions/checkout@v5

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Release

    - name: Package
      run: |
        mkdir release
        copy build\Release\MicLock.exe release\
        powershell Compress-Archive -Path release\* -DestinationPath MicLock-x64.zip

    - name: Upload Artifact
      uses: actions/upload-artifact@v5
      with:
        name: MicLock-x64
        path: MicLock-x64.zip
